"""
Configuración del nicho EcoCuriosa y catálogo editorial de artículos Evergreen.
"""

CATEGORIES = {
    'fauna-fascinante': {
        'name': 'Fauna Fascinante',
        'description': 'Adaptaciones evolutivas, etología y supervivencia animal.',
        'color': '#d97706', # amber-600
    },
    'especies-marinas': {
        'name': 'Especies Marinas',
        'description': 'Secretos de los océanos, criaturas abisales y arrecifes.',
        'color': '#0284c7', # sky-600
    },
    'fenomenos-naturales': {
        'name': 'Fenómenos Naturales',
        'description': 'Fuerzas geológicas, eventos atmosféricos y rarezas planetarias.',
        'color': '#059669', # emerald-600
    },
    'ciencia-curiosa': {
        'name': 'Ciencia Curiosa',
        'description': 'Respuestas científicas rigurosas a misterios cotidianos de la naturaleza.',
        'color': '#7c3aed', # violet-600
    },
}

ARTICLES_DATA = [
    # --- FAUNA FASCINANTE (8 Artículos) ---
    {
        'slug': 'leopardo-de-las-nieves-adaptaciones-frio-extremo',
        'category': 'fauna-fascinante',
        'title': 'El Leopardo de las Nieves: Cómo Sobrevive el Fantasma de las Montañas',
        'description': 'Descubre las asombrosas adaptaciones anatómicas y térmicas que permiten al leopardo de las nieves prosperar a más de 4.000 metros de altitud.',
        'image': '/images/articles/leopardo-de-las-nieves-montana.svg',
        'imageAlt': 'Ilustración detallada de un leopardo de las nieves con denso pelaje gris moteado sobre una cresta rocosa helada en el Himalaya.',
        'tags': ['fauna', 'felinos', 'adaptacion', 'himalaya'],
        'featured': True,
        'author': 'Dr. Alejandro Morales (Biólogo Evolutivo)',
        'search_intent': '¿Cómo se adapta el leopardo de las nieves al frío extremo y la altitud?',
    },
    {
        'slug': 'vuelo-silencioso-buho-real-aerodinamica',
        'category': 'fauna-fascinante',
        'title': 'El Secreto del Vuelo Silencioso del Búho Real: Física y Aerodinámica Plumar',
        'description': 'Análisis de la microestructura del borde de ataque de las plumas del búho que cancela las turbulencias sonoras y lo convierte en el cazador nocturno perfecto.',
        'image': '/images/articles/vuelo-silencioso-buho-real.svg',
        'imageAlt': 'Primer plano esquemático de las plumas desflecadas de las alas de un búho disipando las ondas de fricción del aire durante el vuelo nocturno.',
        'tags': ['aves', 'acustica', 'biomimesis', 'depredadores'],
        'featured': False,
        'author': 'Laura S. Méndez (Ornitóloga)',
        'search_intent': '¿Por qué el vuelo de los búhos no hace ruido?',
    },
    {
        'slug': 'camaleon-pantera-fisica-cambio-color-nanocristales',
        'category': 'fauna-fascinante',
        'title': 'El Camaleón Pantera: La Nanotecnología Natural tras su Cambio de Color',
        'description': 'A diferencia del mito popular, los camaleones no mezclan pigmentos químicos, sino que afinan nanocristales de guanina en su piel como prismas ópticos.',
        'image': '/images/articles/camaleon-pantera-nanocristales.svg',
        'imageAlt': 'Camaleón pantera sobre una rama tropical mostrando un gradiente de iridiscencia entre verde esmeralda y turquesa brillante.',
        'tags': ['reptiles', 'optica', 'nanocristales', 'madagascar'],
        'featured': False,
        'author': 'Carlos V. Ortega (Herpetólogo)',
        'search_intent': '¿Cómo cambian de color los camaleones realmente?',
    },
    {
        'slug': 'pangolin-gigante-armadura-queratina-amenazas',
        'category': 'fauna-fascinante',
        'title': 'El Pangolín Gigante: Anatomía de la Única Armadura Viviente de Queratina',
        'description': 'Explora la armadura biológica del mamífero más traficado del mundo, su sorprendente fuerza defensiva y su rol crucial en el control de insectos.',
        'image': '/images/articles/pangolin-gigante-armadura.svg',
        'imageAlt': 'Pangolín enroscado en una esfera perfecta mostrando sus escamas romboidales protectoras de queratina pura.',
        'tags': ['mamiferos', 'conservacion', 'anatomia', 'biodiversidad'],
        'featured': False,
        'author': 'Equipo Editorial EcoCuriosa',
        'search_intent': '¿De qué están hechas las escamas del pangolín y para qué sirven?',
    },
    {
        'slug': 'memoria-elefante-africano-estructura-cerebral',
        'category': 'fauna-fascinante',
        'title': 'La Memoria del Elefante Africano: ¿Mito o Prodigio Neurológico?',
        'description': 'Cómo el hipocampo y la corteza cerebral del elefante les permiten recordar rutas migratorias a lo largo de décadas y reconocer a cientos de congéneres.',
        'image': '/images/articles/memoria-elefante-africano.svg',
        'imageAlt': 'Manada de elefantes africanos guiada por una matriarca anciana atravesando una llanura de sabana hacia un abrevadero lejano.',
        'tags': ['etologia', 'neurologia', 'elefantes', 'sabana'],
        'featured': False,
        'author': 'Dr. Alejandro Morales (Biólogo Evolutivo)',
        'search_intent': '¿Es real que los elefantes tienen una memoria prodigiosa?',
    },
    {
        'slug': 'axolote-mexicano-regeneracion-tejidos-celulas-madre',
        'category': 'fauna-fascinante',
        'title': 'El Axolote Mexicano y el Misterio de la Regeneración Celular Completa',
        'description': 'El anfibio que no envejece y es capaz de reconstruir extremidades, médula espinal y fragmentos de su propio corazón sin dejar cicatrices.',
        'image': '/images/articles/axolote-mexicano-regeneracion.svg',
        'imageAlt': 'Axolote rosa nadando en agua dulce con sus branquias externas plumosas extendidas y ojos oscuros atentos.',
        'tags': ['anfibios', 'genetica', 'medicina', 'mexico'],
        'featured': False,
        'author': 'Carlos V. Ortega (Herpetólogo)',
        'search_intent': '¿Cómo regenera sus extremidades el axolote mexicano?',
    },
    {
        'slug': 'geco-adherencia-van-der-waals-fuerzas-microscopicas',
        'category': 'fauna-fascinante',
        'title': 'Cómo Caminan los Gecos por el Cristal: La Fuerza de Van der Waals',
        'description': 'Ni pegamento ni ventosas: millones de filamentos microscópicos llamados setas permiten a los gecos interactuar directamente con los electrones de cualquier superficie.',
        'image': '/images/articles/geco-patas-adherencia.svg',
        'imageAlt': 'Detalle microscópico de las almohadillas digitales de un geco mostrando las microfibras ramificadas que generan adhesión molecular.',
        'tags': ['fisica', 'reptiles', 'nanotecnologia', 'biomimetica'],
        'featured': False,
        'author': 'Laura S. Méndez (Bióloga)',
        'search_intent': '¿Por qué los gecos pueden caminar boca abajo en el vidrio?',
    },
    {
        'slug': 'oso-tardigrado-criptobiosis-supervivencia-espacio',
        'category': 'fauna-fascinante',
        'title': 'Los Tardígrados: El Animal Microscópico que Sobrevive al Vacío del Espacio',
        'description': 'A través del estado de criptobiosis, los osos de agua resisten radiación letal, temperaturas de casi cero absoluto y presiones de fosas marinas.',
        'image': '/images/articles/oso-tardigrado-microscopio.svg',
        'imageAlt': 'Ilustración científica en microscopía electrónica de un tardígrado desplazándose sobre una capa de musgo húmedo.',
        'tags': ['microbiologia', 'astrobiologia', 'criptobiosis', 'extremofilos'],
        'featured': False,
        'author': 'Dra. Elena Ramos (Microbióloga)',
        'search_intent': '¿Qué hace tan indestructible al tardígrado?',
    },

    # --- ESPECIES MARINAS (8 Artículos) ---
    {
        'slug': 'calamar-gigante-architeuthis-dux-bioluminiscencia',
        'category': 'especies-marinas',
        'title': 'Architeuthis Dux: La Vida en la Oscuridad Total del Calamar Gigante',
        'description': 'Ojos del tamaño de platos de comida, sangre azul a base de cobre y tentáculos de hasta doce metros adaptados a la zona batipelágica del planeta.',
        'image': '/images/articles/calamar-gigante-abisal.svg',
        'imageAlt': 'Calamar gigante sumergido en las profundidades marinas oscuras con tenues reflejos azulados y ojos enormes adaptados a la penumbra.',
        'tags': ['oceano', 'abisal', 'cefalopodos', 'gigantismo'],
        'featured': False,
        'author': 'Dr. Marcos Peñaloza (Oceanógrafo)',
        'search_intent': '¿Cuánto mide y cómo vive el calamar gigante en el fondo del mar?',
    },
    {
        'slug': 'tiburon-de-groenlandia-vertebrado-mas-longevo',
        'category': 'especies-marinas',
        'title': 'El Tiburón de Groenlandia: El Secreto del Vertebrado que Vive 400 Años',
        'description': 'Metabolismo ultralento, aguas gélidas y un tejido celular resistente al envejecimiento sitúan al tiburón de Groenlandia como el rey indiscutible de la longevidad.',
        'image': '/images/articles/tiburon-de-groenlandia.svg',
        'imageAlt': 'Tiburón de Groenlandia de piel grisácea y movimientos lentos nadando bajo una gruesa capa de hielo ártico.',
        'tags': ['tiburones', 'longevidad', 'artico', 'fisiologia'],
        'featured': False,
        'author': 'Dr. Marcos Peñaloza (Oceanógrafo)',
        'search_intent': '¿Por qué el tiburón de Groenlandia vive tantos siglos?',
    },
    {
        'slug': 'pulpo-mimo-thaumoctopus-mimetismo-15-especies',
        'category': 'especies-marinas',
        'title': 'El Pulpo Mimo: El Genio Marino Capaz de Imitar a 15 Especies Distintas',
        'description': 'No solo cambia de textura y color: el Thaumoctopus mimicus adopta la postura física de peces león, serpientes marinas venenosas y lenguados.',
        'image': '/images/articles/pulpo-mimo-camuflaje.svg',
        'imageAlt': 'Pulpo mimo en el fondo arenoso de Indonesia transformando la disposición de sus brazos para imitar las espinas de un pez león.',
        'tags': ['cefalopodos', 'mimetismo', 'conducta', 'arrecifes'],
        'featured': False,
        'author': 'Laura S. Méndez (Bióloga Marina)',
        'search_intent': '¿Qué animales puede imitar el pulpo mimo y cómo lo hace?',
    },
    {
        'slug': 'arrecifes-de-coral-simbiosis-zooxantelas-blanqueamiento',
        'category': 'especies-marinas',
        'title': 'Los Arrecifes de Coral: La Alianza Secreta entre Pólipos y Algas Microscópicas',
        'description': 'Cómo la simbiosis con las microalgas zooxantelas crea las estructuras vivas más grandes del planeta y qué ocurre a nivel celular durante el blanqueamiento.',
        'image': '/images/articles/arrecife-coral-zooxantelas.svg',
        'imageAlt': 'Primer plano macroscópico de pólipos de coral ramificados con colores vibrantes alimentándose bajo corrientes marinas transparentes.',
        'tags': ['corales', 'ecologia', 'simbiosis', 'cambio-climatico'],
        'featured': False,
        'author': 'Equipo Editorial EcoCuriosa',
        'search_intent': '¿Por qué los corales son animales y no plantas?',
    },
    {
        'slug': 'narval-unicornio-marino-colmillo-sensorial',
        'category': 'especies-marinas',
        'title': 'El Narval y su Colmillo Helicoidal: Un Radar Sensorial en Aguas Heladas',
        'description': 'Lejos de ser un arma de combate, el famoso colmillo del narval es un órgano sensitivo con diez millones de terminaciones nerviosas hidrodinámicas.',
        'image': '/images/articles/narval-colmillo-artico.svg',
        'imageAlt': 'Grupo de narvales asomando sus largos colmillos espirales a través de una grieta en la banquisa helada del Ártico.',
        'tags': ['cetaceos', 'artico', 'evolucion', 'sensorial'],
        'featured': False,
        'author': 'Dr. Marcos Peñaloza (Oceanógrafo)',
        'search_intent': '¿Para qué sirve verdaderamente el cuerno o colmillo del narval?',
    },
    {
        'slug': 'ballena-azul-fisiologia-gigante-cardiovascular',
        'category': 'especies-marinas',
        'title': 'La Fisiología de la Ballena Azul: Un Corazón de 180 Kilos y Arterias Colosales',
        'description': 'Las asombrosas dimensiones y exigencias metabólicas del animal más grande que jamás haya existido en la historia del planeta Tierra.',
        'image': '/images/articles/ballena-azul-gigante.svg',
        'imageAlt': 'Perfil hidrodinámico monumental de una ballena azul surcando aguas oceánicas profundas con el kril rodeando su mandíbula.',
        'tags': ['cetaceos', 'gigantismo', 'fisiologia', 'mar'],
        'featured': False,
        'author': 'Dra. Sofía Alarcón (Zoóloga Marina)',
        'search_intent': '¿Cómo bombea sangre el corazón de una ballena azul?',
    },
    {
        'slug': 'pez-abrecaminos-bioluminiscencia-pez-linterna',
        'category': 'especies-marinas',
        'title': 'Peces Abisales y Bioluminiscencia: La Batalla de Luz en la Zona de Medianoche',
        'description': 'Reacciones luciferina-luciferasa y órganos fotóforos: cómo los habitantes de las fosas oceánicas cazan, se comunican y evaden depredadores.',
        'image': '/images/articles/pez-linterna-bioluminiscente.svg',
        'imageAlt': 'Pez linterna abisal con su apéndice bioluminiscente brillando con luz esmeralda en medio del abismo negro.',
        'tags': ['bioluminiscencia', 'abisal', 'quimica', 'ictiologia'],
        'featured': False,
        'author': 'Dr. Marcos Peñaloza (Oceanógrafo)',
        'search_intent': '¿Cómo producen luz los peces en el fondo del océano?',
    },
    {
        'slug': 'manta-raya-gigante-inteligencia-cerebro-peces',
        'category': 'especies-marinas',
        'title': 'La Manta Raya Gigante: El Cerebro más Grande y Complejo de los Peces',
        'description': 'Investigaciones cognitivas recientes revelan que las mantas gigantes poseen autoconciencia frente a espejos y elaborados mapas de navegación oceánica.',
        'image': '/images/articles/manta-raya-gigante.svg',
        'imageAlt': 'Manta raya gigante con sus alas pectorales desplegadas planeando elegantemente sobre una estación de limpieza en el arrecife.',
        'tags': ['ictiologia', 'cognicion', 'arrecifes', 'peces'],
        'featured': False,
        'author': 'Laura S. Méndez (Bióloga Marina)',
        'search_intent': '¿Qué tan inteligentes son las mantas rayas?',
    },

    # --- FENÓMENOS NATURALES (8 Artículos) ---
    {
        'slug': 'auroras-boreales-viento-solar-magnetosfera',
        'category': 'fenomenos-naturales',
        'title': 'Auroras Boreales: La Danza Magnética entre el Sol y la Atmósfera Terrestre',
        'description': 'Física de partículas explicada paso a paso: colisiones de electrones solares con átomos de oxígeno y nitrógeno a 100 kilómetros de altura.',
        'image': '/images/articles/auroras-boreales-cielo.svg',
        'imageAlt': 'Cielo nocturno polar teñido de cortinas ondulantes de luz verde esmeralda y violeta sobre un lago congelado.',
        'tags': ['atmosfera', 'geofisica', 'magnetosfera', 'artico'],
        'featured': False,
        'author': 'Dr. Fernando Ibáñez (Astrofísico)',
        'search_intent': '¿Qué causa las auroras boreales y por qué tienen diferentes colores?',
    },
    {
        'slug': 'relampago-del-catatumbo-tormenta-eterna-venezuela',
        'category': 'fenomenos-naturales',
        'title': 'El Relámpago del Catatumbo: La Tormenta que Nunca Termina en el Lago de Maracaibo',
        'description': 'Hasta 260 noches al año de descargas eléctricas continuas: la orografía de la cordillera andina y los vientos termales que alimentan el mayor regenerador de ozono.',
        'image': '/images/articles/relampago-del-catatumbo.svg',
        'imageAlt': 'Múltiples rayos eléctricos bifurcándose e iluminando nubes de tormenta densas sobre las aguas del lago Maracaibo.',
        'tags': ['meteorologia', 'rayos', 'clima', 'venezuela'],
        'featured': False,
        'author': 'Equipo Editorial EcoCuriosa',
        'search_intent': '¿Por qué caen tantos rayos en el relámpago del Catatumbo?',
    },
    {
        'slug': 'mar-de-ardora-bioluminiscencia-noctiluca-scintillans',
        'category': 'fenomenos-naturales',
        'title': 'El Mar de Ardora: Cuando las Olas Brillan con Luz Neón en la Orilla',
        'description': 'El dinoflagelado Noctiluca scintillans convierte la energía del oleaje en destellos azules por fricción mecánica para ahuyentar a sus depredadores.',
        'image': '/images/articles/mar-de-ardora-playa.svg',
        'imageAlt': 'Orilla de una playa nocturna rompiendo en espuma azul fluorescente brillante bajo un cielo estrellado.',
        'tags': ['bioluminiscencia', 'microalgas', 'costas', 'fenomenos'],
        'featured': False,
        'author': 'Laura S. Méndez (Bióloga)',
        'search_intent': '¿Qué es el mar de ardora y en qué playas ocurre?',
    },
    {
        'slug': 'piedras-rodantes-playa-valle-de-la-muerte-racetrack',
        'category': 'fenomenos-naturales',
        'title': 'Las Piedras Rodantes de Racetrack Playa: El Enigma Geológico Resuelto',
        'description': 'Rocas de cientos de kilos que se desplazan dejando surcos misteriosos en el desierto: la combinación exacta de finas placas de hielo, agua y viento moderado.',
        'image': '/images/articles/piedras-rodantes-racetrack.svg',
        'imageAlt': 'Roca solitaria sobre el lecho de arcilla agrietada del Valle de la Muerte dejando una larga huella recta detrás de su trayecto.',
        'tags': ['geologia', 'desiertos', 'misterios', 'clima'],
        'featured': False,
        'author': 'Dr. Fernando Ibáñez (Geofísico)',
        'search_intent': '¿Cómo se mueven las piedras del Valle de la Muerte?',
    },
    {
        'slug': 'agujeros-azules-oceano-sinkholes-formacion-geologica',
        'category': 'fenomenos-naturales',
        'title': 'Los Agujeros Azules del Océano: Cavernas Glaciares Inundadas por el Mar',
        'description': 'Cómo las oscilaciones del nivel del mar en las eras glaciales excavaron los mayores sumideros cársticos submarinos del planeta, como el Gran Agujero Azul de Belice.',
        'image': '/images/articles/agujero-azul-belice.svg',
        'imageAlt': 'Vista aérea circular del Gran Agujero Azul con su contorno turquesa rodeado de arrecifes de coral vivos en Belice.',
        'tags': ['geologia', 'oceanografia', 'cavernas', 'belice'],
        'featured': False,
        'author': 'Dr. Marcos Peñaloza (Oceanógrafo)',
        'search_intent': '¿Cómo se forman los agujeros azules submarinos?',
    },
    {
        'slug': 'calentamiento-estratosferico-repentino-vortice-polar',
        'category': 'fenomenos-naturales',
        'title': 'El Vórtice Polar y el Calentamiento Estratosférico: Cómo se Congela un Continente',
        'description': 'Dinámica de fluidos en la alta atmósfera: el debilitamiento de los vientos circumpolares que deja escapar masas de aire ártico a latitudes templadas.',
        'image': '/images/articles/vortice-polar-estratosfera.svg',
        'imageAlt': 'Esquema atmosférico del planeta Tierra mostrando el anillo del vórtice polar deformándose y desplazando aire frío hacia el sur.',
        'tags': ['climatologia', 'meteorologia', 'vortice-polar', 'invierno'],
        'featured': False,
        'author': 'Dra. Carmen Rivas (Meteoróloga)',
        'search_intent': '¿Qué es el vórtice polar y por qué provoca olas de frío extremo?',
    },
    {
        'slug': 'nubes-mastodonticas-mammatus-gravedad-humedad',
        'category': 'fenomenos-naturales',
        'title': 'Nubes Mammatus: Las Bolsas Colgantes que Anuncian Tormentas Severas',
        'description': 'Inversión de las corrientes convectivas: por qué estas espectaculares bolsas de condensación se forman colgando hacia abajo en los yunques de cumulonimbus.',
        'image': '/images/articles/nubes-mammatus-cielo.svg',
        'imageAlt': 'Cielo cubierto de protuberancias globulares doradas y azuladas colgando de la base de una gran nube de tormenta.',
        'tags': ['meteorologia', 'nubes', 'tormentas', 'atmosfera'],
        'featured': False,
        'author': 'Dra. Carmen Rivas (Meteoróloga)',
        'search_intent': '¿Por qué se forman las nubes con forma de bolsa (mammatus)?',
    },
    {
        'slug': 'geiseres-hidrotermales-mecanismo-erupcion-presion',
        'category': 'fenomenos-naturales',
        'title': 'La Física de los Géiseres: Cómo una Cámara Subterránea Detona Columnas de Vapor',
        'description': 'Punto de ebullición dependiente de la presión hidrostática: la cadena termodinámica que hace estallar géiseres como el Old Faithful con precisión de reloj.',
        'image': '/images/articles/geiser-erupcion-vapor.svg',
        'imageAlt': 'Impresionante columna vertical de agua hirviente y vapor blanco elevándose hacia el cielo desde una cuenca geotérmica humeante.',
        'tags': ['geotermia', 'vulcanologia', 'termodinamica', 'tierra'],
        'featured': False,
        'author': 'Equipo Editorial EcoCuriosa',
        'search_intent': '¿Cómo funciona un géiser por dentro y por qué expulsa agua a intervalos?',
    },

    # --- CIENCIA CURIOSA (8 Artículos) ---
    {
        'slug': 'por-que-el-cielo-es-azul-dispersion-rayleigh',
        'category': 'ciencia-curiosa',
        'title': '¿Por Qué el Cielo es Azul y los Atardeceres Rojos? La Dispersión de Rayleigh',
        'description': 'La luz solar parece blanca, pero viaja en todas las longitudes de onda. Explicación paso a paso de cómo los gases atmosféricos dispersan preferentemente la luz azul.',
        'image': '/images/articles/dispersion-rayleigh-cielo-azul.svg',
        'imageAlt': 'Haz de luz solar incidiendo sobre las moléculas atmosféricas y dispersando rayos azules mientras los tonos cálidos atraviesan el horizonte.',
        'tags': ['optica', 'fisica', 'cielo', 'luz'],
        'featured': False,
        'author': 'Dr. Fernando Ibáñez (Físico)',
        'search_intent': '¿Por qué el cielo es azul explicado de forma sencilla?',
    },
    {
        'slug': 'por-que-el-agua-hierve-a-menor-temperatura-montana',
        'category': 'ciencia-curiosa',
        'title': 'Por Qué el Agua Hierve a Menos de 100 °C en la Montaña: Presión y Ebullición',
        'description': 'A nivel del mar el agua hierve a 100 °C, pero en la cima del Everest lo hace a tan solo 71 °C. Entiende la relación termodinámica entre presión atmosférica y vapor.',
        'image': '/images/articles/ebullicion-agua-montana.svg',
        'imageAlt': 'Olla con agua en ebullición sobre una hornilla portátil en un campamento de alta montaña nevada.',
        'tags': ['termodinamica', 'quimica', 'altitud', 'cocina-cientifica'],
        'featured': False,
        'author': 'Dr. Fernando Ibáñez (Físico)',
        'search_intent': '¿Por qué el agua hierve antes en lugares altos?',
    },
    {
        'slug': 'por-que-es-contagioso-el-bostezo-neuronas-espejo',
        'category': 'ciencia-curiosa',
        'title': 'El Enigma del Bostezo Contagioso: Neuronas Espejo, Empatía y Termorregulación',
        'description': 'Neurociencia del reflejo imitativo: por qué ver o escuchar a alguien bostezar activa zonas parietales asociadas a la vinculación social y el enfriamiento cerebral.',
        'image': '/images/articles/bostezo-contagioso-neurociencia.svg',
        'imageAlt': 'Representación artística de las conexiones neuronales que se iluminan en el córtex cerebral ante el estímulo de un bostezo ajeno.',
        'tags': ['neurociencia', 'psicologia', 'evolucion', 'fisiologia'],
        'featured': False,
        'author': 'Dra. Sofía Alarcón (Neurobióloga)',
        'search_intent': '¿Por qué nos contagiamos el bostezo cuando vemos a alguien hacerlo?',
    },
    {
        'slug': 'como-recuerdan-las-plantas-invierno-epigenetica-vernalizacion',
        'category': 'ciencia-curiosa',
        'title': 'Cómo Saben las Plantas Cuándo Florecer: La Memoria Molecular del Invierno',
        'description': 'Las plantas no tienen cerebro pero cuentan los días fríos mediante la vernalización: interruptores epigenéticos que bloquean la floración hasta la primavera.',
        'image': '/images/articles/vernalizacion-plantas-brote.svg',
        'imageAlt': 'Pequeño brote verde emergiendo con vigor a través de una fina capa de escarcha matutina primaveral.',
        'tags': ['botanica', 'epigenetica', 'primavera', 'plantas'],
        'featured': False,
        'author': 'Dra. Elena Ramos (Bióloga Celular)',
        'search_intent': '¿Cómo saben las plantas cuándo ha terminado el invierno?',
    },
    {
        'slug': 'como-funciona-el-campo-magnetico-de-la-tierra-geodinamo',
        'category': 'ciencia-curiosa',
        'title': 'El Escudo Invisible del Planeta: Cómo Funciona el Efecto Geodinamo Terrestre',
        'description': 'A 3.000 kilómetros bajo nuestros pies, un océano de hierro líquido en rotación crea el campo magnético que impide que el viento solar barra nuestra atmósfera.',
        'image': '/images/articles/campo-magnetico-geodinamo.svg',
        'imageAlt': 'Corte transversal esquemático de la Tierra mostrando el núcleo fundido en rotación y las líneas magnéticas envolventes que desvían la radiación solar.',
        'tags': ['geofisica', 'planeta', 'magnetismo', 'tierra'],
        'featured': False,
        'author': 'Dr. Fernando Ibáñez (Geofísico)',
        'search_intent': '¿Cómo se genera el campo magnético de la Tierra y por qué es vital?',
    },
    {
        'slug': 'por-que-las-cebras-tienen-rayas-termoregulacion-moscas',
        'category': 'ciencia-curiosa',
        'title': 'El Fin del Misterio de las Rayas de las Cebras: Ni Camuflaje ni Identidad',
        'description': 'Experimentos ópticos modernos desvelan que el patrón blanco y negro polariza la luz de una forma que aturde el sistema visual de los tábanos y moscas transmisoras de parásitos.',
        'image': '/images/articles/cebra-rayas-optica.svg',
        'imageAlt': 'Primer plano geométrico de las rayas diagonales de una cebra creando un contraste óptico bajo el sol de la sabana.',
        'tags': ['zoologia', 'optica', 'evolucion', 'insectos'],
        'featured': False,
        'author': 'Dr. Alejandro Morales (Biólogo Evolutivo)',
        'search_intent': '¿Para qué sirven las rayas de las cebras según la ciencia?',
    },
    {
        'slug': 'por-que-el-olor-a-tierra-mojada-petricor-geosmina',
        'category': 'ciencia-curiosa',
        'title': 'La Química del Petricor: Por Qué Amamos el Inconfundible Olor a Tierra Mojada',
        'description': 'La geosmina producida por bacterias del suelo (Actinomyces) y los aerosoles liberados por las gotas de lluvia activan un receptor olfativo hipersensible en el ser humano.',
        'image': '/images/articles/petricor-gotas-lluvia-tierra.svg',
        'imageAlt': 'Gota de lluvia impactando contra la tierra húmeda liberando microaerosoles iluminados por un rayo de sol suave.',
        'tags': ['quimica', 'olores', 'lluvia', 'evolucion'],
        'featured': False,
        'author': 'Dra. Elena Ramos (Bioquímica)',
        'search_intent': '¿Cómo se llama y qué produce el olor a tierra mojada?',
    },
    {
        'slug': 'por-que-los-gatos-ronronean-frecuencia-sanacion-osea',
        'category': 'ciencia-curiosa',
        'title': 'La Acústica del Ronroneo Felino: Frecuencias de 25 a 150 Hz y Regeneración Celular',
        'description': 'Los felinos no ronronean solo por placer: la vibración continua de sus cuerdas vocales funciona como un mecanismo biomecánico de recuperación ósea y tisular.',
        'image': '/images/articles/ronroneo-felino-acustica.svg',
        'imageAlt': 'Gato doméstico descansando plácidamente mientras emite vibraciones corporales representadas como suaves ondas sinusoidales.',
        'tags': ['veterinaria', 'felinos', 'acustica', 'salud-animal'],
        'featured': False,
        'author': 'Dra. Sofía Alarcón (Zoóloga)',
        'search_intent': '¿Por qué ronronean los gatos y qué efecto tiene en su cuerpo?',
    },
]
